# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import idm_pb2 as idm__pb2


class IdmServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePatient = channel.unary_unary(
                '/model.IdmService/CreatePatient',
                request_serializer=idm__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=idm__pb2.UserResponse.FromString,
                )
        self.CreatePhysician = channel.unary_unary(
                '/model.IdmService/CreatePhysician',
                request_serializer=idm__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=idm__pb2.UserResponse.FromString,
                )
        self.UpdateInfo = channel.unary_unary(
                '/model.IdmService/UpdateInfo',
                request_serializer=idm__pb2.UpdateInfoRequest.SerializeToString,
                response_deserializer=idm__pb2.UserResponse.FromString,
                )
        self.SetRole = channel.unary_unary(
                '/model.IdmService/SetRole',
                request_serializer=idm__pb2.SetRoleRequest.SerializeToString,
                response_deserializer=idm__pb2.UserResponse.FromString,
                )
        self.GetRoles = channel.unary_unary(
                '/model.IdmService/GetRoles',
                request_serializer=idm__pb2.GetRolesRequest.SerializeToString,
                response_deserializer=idm__pb2.RolesResponse.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/model.IdmService/GetUser',
                request_serializer=idm__pb2.GetUserRequest.SerializeToString,
                response_deserializer=idm__pb2.UserResponse.FromString,
                )
        self.GetUsers = channel.unary_unary(
                '/model.IdmService/GetUsers',
                request_serializer=idm__pb2.GetUsersRequest.SerializeToString,
                response_deserializer=idm__pb2.UsersResponse.FromString,
                )
        self.Login = channel.unary_unary(
                '/model.IdmService/Login',
                request_serializer=idm__pb2.LoginRequest.SerializeToString,
                response_deserializer=idm__pb2.LoginResponse.FromString,
                )
        self.Logout = channel.unary_unary(
                '/model.IdmService/Logout',
                request_serializer=idm__pb2.LogoutRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.Authorize = channel.unary_unary(
                '/model.IdmService/Authorize',
                request_serializer=idm__pb2.AuthorizeRequest.SerializeToString,
                response_deserializer=idm__pb2.UserResponse.FromString,
                )
        self.DeletePhysician = channel.unary_unary(
                '/model.IdmService/DeletePhysician',
                request_serializer=idm__pb2.DeletePhysicianRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class IdmServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePatient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePhysician(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Authorize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePhysician(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdmServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePatient': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePatient,
                    request_deserializer=idm__pb2.CreateUserRequest.FromString,
                    response_serializer=idm__pb2.UserResponse.SerializeToString,
            ),
            'CreatePhysician': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePhysician,
                    request_deserializer=idm__pb2.CreateUserRequest.FromString,
                    response_serializer=idm__pb2.UserResponse.SerializeToString,
            ),
            'UpdateInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInfo,
                    request_deserializer=idm__pb2.UpdateInfoRequest.FromString,
                    response_serializer=idm__pb2.UserResponse.SerializeToString,
            ),
            'SetRole': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRole,
                    request_deserializer=idm__pb2.SetRoleRequest.FromString,
                    response_serializer=idm__pb2.UserResponse.SerializeToString,
            ),
            'GetRoles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoles,
                    request_deserializer=idm__pb2.GetRolesRequest.FromString,
                    response_serializer=idm__pb2.RolesResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=idm__pb2.GetUserRequest.FromString,
                    response_serializer=idm__pb2.UserResponse.SerializeToString,
            ),
            'GetUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsers,
                    request_deserializer=idm__pb2.GetUsersRequest.FromString,
                    response_serializer=idm__pb2.UsersResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=idm__pb2.LoginRequest.FromString,
                    response_serializer=idm__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=idm__pb2.LogoutRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Authorize': grpc.unary_unary_rpc_method_handler(
                    servicer.Authorize,
                    request_deserializer=idm__pb2.AuthorizeRequest.FromString,
                    response_serializer=idm__pb2.UserResponse.SerializeToString,
            ),
            'DeletePhysician': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePhysician,
                    request_deserializer=idm__pb2.DeletePhysicianRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model.IdmService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IdmService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePatient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.IdmService/CreatePatient',
            idm__pb2.CreateUserRequest.SerializeToString,
            idm__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePhysician(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.IdmService/CreatePhysician',
            idm__pb2.CreateUserRequest.SerializeToString,
            idm__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.IdmService/UpdateInfo',
            idm__pb2.UpdateInfoRequest.SerializeToString,
            idm__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.IdmService/SetRole',
            idm__pb2.SetRoleRequest.SerializeToString,
            idm__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRoles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.IdmService/GetRoles',
            idm__pb2.GetRolesRequest.SerializeToString,
            idm__pb2.RolesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.IdmService/GetUser',
            idm__pb2.GetUserRequest.SerializeToString,
            idm__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.IdmService/GetUsers',
            idm__pb2.GetUsersRequest.SerializeToString,
            idm__pb2.UsersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.IdmService/Login',
            idm__pb2.LoginRequest.SerializeToString,
            idm__pb2.LoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.IdmService/Logout',
            idm__pb2.LogoutRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Authorize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.IdmService/Authorize',
            idm__pb2.AuthorizeRequest.SerializeToString,
            idm__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePhysician(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/model.IdmService/DeletePhysician',
            idm__pb2.DeletePhysicianRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
